### ISSUE TITLE
Reporter fails with Mocha 4.0.0

### ISSUE THREAD

**Issue by Kporal** [adamgruber/mochawesome#192]
# Issue

When using mochawesome [2.3.1](https://github.com/adamgruber/mochawesome/releases/tag/2.3.1) with Mocha [4.0.0](https://github.com/mochajs/mocha/releases/tag/v4.0.0) the reporter fails when I've errors in my tests.

I've the following error in the console:
```
/test/node_modules/mocha/lib/reporters/base.js:227
    test.titlePath().forEach(function (str, index) {
         ^

TypeError: test.titlePath is not a function
    at /test/node_modules/mocha/lib/reporters/base.js:227:10
    at Array.forEach (<anonymous>)
    at Function.exports.list (/test/node_modules/mocha/lib/reporters/base.js:167:12)
    at Spec.Base.epilogue (/test/node_modules/mocha/lib/reporters/base.js:344:10)
    at emitNone (events.js:110:20)
    at Runner.emit (events.js:207:7)
    at /test/node_modules/codeceptjs-webdriverio/node_modules/mocha/lib/runner.js:812:12
    at done (/test/node_modules/codeceptjs-webdriverio/node_modules/mocha/lib/runner.js:649:7)
    at Runner.next [as nextSuite] (/test/node_modules/codeceptjs-webdriverio/node_modules/mocha/lib/runner.js:616:16)
    at Runner.uncaught (/test/node_modules/codeceptjs-webdriverio/node_modules/mocha/lib/runner.js:737:17)
```

It seems to be caused by this [change](https://github.com/mochajs/mocha/pull/2814) from the 4.0.0 release of Mocha.

# How to reproduce

Create a `test.js` which generates an error and run `mocha test.js --reporter mochawesome`

**Comment by adamgruber** [comment]
@Kporal Can you provide some actual code that reproduces this issue? I tried creating a failing test as you suggest but did not get the error.
```js
// test.js
const chai = require('chai');
chai.should();

describe('test', () => {
  it('fails', () => {
    (1 + 1).should.eql(3);
  });
});
```

**Comment by Kporal** [comment]
@adamgruber you're right. I found out that this bug is due to codeceptjs. It's the tool that I am using for running my E2E tests. I will open an issue on their Github repository and will close this one. Thanks
