### ISSUE TITLE
Does not display actual and expected result

### ISSUE THREAD

**Issue by fergadipa** [adamgruber/mochawesome#210]
Dear mochawesome,

First of all, thank you for provide mochawesome report.
I have a problem when there is a failure on my test, mochawesome does not show actual and expected result as shown on sample report on this repo.

```
TypeError: Cannot read property 'customer' of undefined

TypeError: Cannot read property 'customer' of undefined
    at tests/api/customer/boCustomerTest.js:36:31
    at Test.<anonymous> (tests/page-objects/api/customer/boCustomer.js:19:13)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:715:3)
    at parser (node_modules/superagent/lib/node/index.js:903:18)
    at IncomingMessage.res.on.e (node_modules/superagent/lib/node/parsers/json.js:19:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
api.get(customerPath + '/' + customerID)
  .set('Authorization', common.bearer(tokenSelection))
  .set('Accept', 'application/json')
  .end(function(err, result) {
    response(result);
    done(err);
})
```

Here is mochawesome command:
`--reporter mochawesome --reporter-options reportDir=reports/mochawesome/`

Do I miss something on command?

Thank you :)

**Comment by adamgruber** [comment]
The command looks ok. The output you are showing looks like there is just an issue with the test itself. Without looking at actual code I cannot really say what's happening here.

**Comment by fergadipa** [comment]
Thank you :)
So here is my code:
```
var should = require ('chai').should(),
expect = require ('chai').expect,
supertest  = require ('supertest'),
api = supertest ('http://staging-api-finance.bizzy.co.id/finance/v1');
var bearer = "Bearer XXXXX";

describe('Customer', function(){
    var id = "120159"; // input invalid id in order to make the test failure
    it('check mandatory fields',function(done){
        api.get('/customer/'+id)
        .set('Authorization',bearer,'application/json')
        .end(function(err,response){
            //console.log(response.body.data[0].customer);
            expect(response.status).to.equal(200);
            expect(response.body.data[0].customer).to.have.property("internal_id");
            expect(response.body.data[0].customer).to.have.property("name");
            done();
        })
    });
    it('should get customer data', function(done){
        api.get('/customer/'+id)
        .set('Authorization',bearer, 'application/json')
        .end(function(err,response){
            expect(response.status).to.equal(200);
            expect(response.body.data[0].customer.internal_id).to.equal(id);
            expect(response.body.data[0].customer.name).to.equal("PT ABCD");
            done();
        })
    });
});
```

Here is my package.json
```
{
  "name": "apitest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "api-test": "node_modules/mocha/bin/mocha test --reporter mochawesome --reporter-options reportDir=reports/mochawesome/"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.18.2",
    "chai": "^4.1.2",
    "express": "^4.16.2",
    "mocha": "^4.0.1",
    "supertest": "^3.0.0"
  },
  "devDependencies": {
    "allure-commandline": "^2.4.1",
    "mocha": "^3.5.3",
    "mochawesome": "^2.3.1"
  }
}
```

**Comment by adamgruber** [comment]
Thanks for the sample code. The problem I'm seeing is that the `api.get` call is actually failing so when we hit the `end()` method, `response` is undefined. So, the test itself is failing before getting to the `expect` calls. Double check your test and make sure that you are getting a response.
