### ISSUE TITLE
Fails with defaults (Cannot read property 'useInlineDiffs' of undefined)

### ISSUE THREAD

**Issue by jasonpolites** [adamgruber/mochawesome#253]
I have been using mocha successfully, however mochawesome fails for me.

### Steps Taken ###

```
npm install --save-dev mochawesome
```
In `package.json`, change the following line:

```
"scripts": {
    "test": "nyc --reporter=html --reporter=text mocha",
```
to
```
"scripts": {
    "test": "nyc --reporter=mochawesome --reporter=text mocha",
```

run `npm test`

Observe this error:

```
[REDACTED]/node_modules/mochawesome/dist/config.js:36
    useInlineDiffs: !!opts.useInlineDiffs
                           ^

TypeError: Cannot read property 'useInlineDiffs' of undefined
    at module.exports (/[REDACTED]/node_modules/mochawesome/dist/config.js:36:28)
    at new Mochawesome (/[REDACTED]/node_modules/mochawesome/dist/mochawesome.js:71:17)
    at Object.create (/[REDACTED]/node_modules/nyc/node_modules/istanbul-reports/index.js:17:16)
    at reporter.forEach (/[REDACTED]/node_modules/nyc/index.js:451:24)
    at Array.forEach (<anonymous>)
    at NYC.report (/[REDACTED]/node_modules/nyc/index.js:450:17)
    at report (/[REDACTED]/node_modules/nyc/bin/nyc.js:89:7)
    at /[REDACTED]/node_modules/nyc/bin/nyc.js:76:25
    at ChildProcess.<anonymous> (/[REDACTED]/node_modules/nyc/node_modules/foreground-child/index.js:52:5)
    at emitTwo (events.js:126:13)
```

**Comment by adamgruber** [comment]
Try moving your `--reporter` options after you call `mocha` like this:
```json
"scripts": {
  "test": "nyc mocha --reporter=mochawesome --reporter=text"
}
```

**Comment by adamgruber** [comment]
Do you not see coverage output to the console or are you asking for the coverage to show in the HTML report as well? If it's the latter then, no, coverage is not built into mochawesome.

**Comment by hasanlussa** [comment]
simply move your mocawesome reporter after mocha command, but keep the text reporter after nyc
```shell
nyc --reporter=text-summary --reporter=text mocha test/build/index.js --reporter=mochawesome
```

**Comment by adamgruber** [comment]
As answered above, this is reporter-flag ordering with `nyc` — put `--reporter` after `mocha` (`nyc mocha --reporter=mochawesome`). Closing as answered.

---
_Triaged and posted via Claude Code, on behalf of @adamgruber._
