### ISSUE TITLE
Unable to add screenshot path to mochawesome report

### ISSUE THREAD

**Issue by TSSumanth** [adamgruber/mochawesome#272]
Issue: When i use the below code to add the screenshots path to mocha report, i could see an image link in the report, clicking on the image link is taking me to an undefined path because the screenshot path is getting appended with path where my mochawesome report is getting stored.

Code: await addContext(this, "ScreenShot Path - "+"file:///"+screenshotpath)

Ex: (Mocharesultspath//file:///screenshotpath)
Sample Path: file:///D:/JavaScript/BryntumFrameworkOverallResults/2019_03_14_08_46_AM/ScreenShot%20Path%20-%20%20-%20file:///D:/JavaScript/BryntumFrameworkOverallResults/2019_03_14_08_46_AM/TestResults/sun683201921431656xli/Screenshots/vgy683201921431656vrh_UpdateDependencyFromCustomEditor/2265Error%20Occured:%20.png

**Comment by TSSumanth** [comment]
@adamgruber it would be really helpful if u provide me any updates on this

**Comment by adamgruber** [comment]
Can you provide a simple repo that reproduces this issue? The code example above is not too useful. Also I am not sure why you are calling `await addContext()` since `addContext` does not return a promise.

**Comment by kolbasik** [comment]
Hi @TSSumanth , you could use DataUri in order to inline images directly to the report.

```js
addContext(this, {
    title: "screenshot",
    value: "data:image/png;base64," + screenshot.toString("base64")
});
```

Or you could put screenshots into the folder with a report and use the relative paths like `./screenshots/screen_1.png`

**Comment by aurnoi1** [comment]
Thanks @kolbasik, it helps me! And thanks @adamgruber, really useful tool :)

**Comment by caidanny** [comment]
hi @kolbasik , could you share the code that converts the image to base64 and and use it in addContext, I'm using Cypress but I'm not sure how to use base64 for the mocha report.

**Comment by ToAM90** [comment]
> hi @kolbasik , could you share the code that converts the image to base64 and and use it in addContext, I'm using Cypress but I'm not sure how to use base64 for the mocha report.

hi @caidanny ! were you able to figure out how to convert the image to base64? I have been trying different things to no avail :( 

this was one of my more recent attempts:
```

Cypress.on('test:after:run', (test, runnable) => {
  if(test.state === 'failed' && test.currentRetry === test.retries){
    const title = test.title.replace('.', "").replace('#', '%23');
    const parentTitle = runnable.parent.title.replace(".", "");
    const filePath = (test.retries == 0) ? 
      `${Cypress.config('screenshotsFolder')}/${Cypress.spec.name}/${parentTitle} -- ${title} (failed).png`
      : `${Cypress.config('screenshotsFolder')}/${Cypress.spec.name}/${parentTitle} -- ${title} (failed) (attempt 2).png`;


    const screenshot = "data:image/png;base64," + Convert.ToBase64String(System.IO.File.ReadAllBytes(filePath));

    addContext({ test }, screenshot); 

  };
})
```

i've also tried image-to-base64 npm package and FileReader too...

**Comment by ToAM90** [comment]
hi @kolbasik ! I just tired it but it is not attaching the image still :( i tried testing by copying the relative path directly for one of the image as well with no luck. do you have any other suggestions? i can attach the screenshot directly with the filePath just fine, but would like to have it added inline so it can be emailed 

```
Cypress.on('test:after:run', (test, runnable) => {
  if(test.state === 'failed' && test.currentRetry === test.retries){
    const title = test.title.replace('.', "").replace('#', '%23');
    const parentTitle = runnable.parent.title.replace(".", "");
    const filePath = (test.retries == 0) ? 
      `${Cypress.config('screenshotsFolder')}/${Cypress.spec.name}/${parentTitle} -- ${title} (failed).png`
      : `${Cypress.config('screenshotsFolder')}/${Cypress.spec.name}/${parentTitle} -- ${title} (failed) (attempt 2).png`;
    const fs = require("fs")
    const pngAsBase64 = fs.readFileSync(filePath, "base64")
    addContext({ test }, "data:image/png;base64," + pngAsBase64);
  };
})
```

i also tried having the filePath wrapped in and without quotes and it didn't do anything either

**Comment by ToAM90** [comment]
So I think the problem is that fs is a nodejs built-in module and cannot be used in Browser. I tried moving the logic to a task plugin in cypress but that didn't solve the problem. It looks like cy.task() just doesn't work or get called? Am currently trying this : 

```
Cypress.on('test:after:run', (test, runnable) => {
  if(test.state === 'failed' && test.currentRetry === test.retries){
    const title = test.title.replace('.', "").replace('#', '%23');
    const parentTitle = runnable.parent.title.replace(".", "");
    const filePath = (test.retries == 0) ? 
      `"${Cypress.config('screenshotsFolder')}/${Cypress.spec.name}/${parentTitle} -- ${title} (failed).png"`
      : `"${Cypress.config('screenshotsFolder')}/${Cypress.spec.name}/${parentTitle} -- ${title} (failed) (attempt 2).png"`

    const root = await navigator.storage.getDirectory();
    const handle = await root.getFileHandle(filePath);
    const file = await handle.getFile();

    var reader = new FileReader();
    const screenshot = reader.readAsDataURL(file);
  
    addContext({ test }, screenshot)

  };
})
```

but` getting error:

```
Error: Pattern ...../cypress/reports/.jsons/*.json matched no report files
    at /Users/4530206/mrvprojects-ui-integration-test/node_modules/mochawesome-merge/lib/index.js:14:11
    at Array.map (<anonymous>)
    at /Users/4530206/mrvprojects-ui-integration-test/node_modules/mochawesome-merge/lib/utils.js:3:46
    at merge (/Users/4530206/mrvprojects-ui-integration-test/node_modules/mochawesome-merge/lib/index.js:84:17)
    at mergeAndCreate (/Users/4530206/mrvprojects-ui-integration-test/node_modules/cypress-mochawesome-reporter/lib/generateReport.js:12:24)
    at generateReport (/Users/4530206/mrvprojects-ui-integration-test/node_modules/cypress-mochawesome-reporter/lib/generateReport.js:55:20)
    at afterRunHook (/Users/4530206/mrvprojects-ui-integration-test/node_modules/cypress-mochawesome-reporter/lib/index.js:51:9)
    at /Users/4530206/mrvprojects-ui-integration-test/node_modules/cypress-mochawesome-reporter/plugin.js:9:11
    at Object.handler (/Users/4530206/mrvprojects-ui-integration-test/node_modules/cypress-on-fix/index.js:32:29)
    at RunPlugins.invoke (/Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:183:18)
    at /Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
    at RunPlugins.execute (/Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:164:21)
    at EventEmitter.<anonymous> (/Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:56:12)
    at EventEmitter.emit (events.js:400:28)
    at EventEmitter.emit (domain.js:475:12)
    at process.<anonymous> (/Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/4530206/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
```

this is how the config looks. There is no problem if I am not running the FileSystem API so not sure what is happening. I need the FileSystem API since FileReader cannot access file by pathname... 

Any ideas on what is going on or if there is another approach I can try to encode the screenshot as base64?

**Comment by thakukr** [comment]
Did we find solution to this ??

**Comment by adamgruber** [comment]
The screenshot "path" is whatever you pass to `addContext`; a local filesystem path only resolves on the machine that has the file, and `fs`-based encoding won't run in a browser/Cypress context. The reliable approach, as @kolbasik showed, is to inline the image as a base64 data URI so it's embedded directly in the report. Closing as answered (related: #309).

---
_Triaged and posted via Claude Code, on behalf of @adamgruber._
