### ISSUE TITLE
Not working with mocha's --recursive option?

### ISSUE THREAD

**Issue by riescorp-iharrison** [adamgruber/mochawesome#41]
Ubuntu 12.04
Mocha 2.4.5
Mochawesome 1.3.2

This works fine:
`mocha test/rsp/date-spec.js --reporter mochawesome`
This runs the tests, but fails on file generation: 
`mocha test --recursive --reporter mochawesome`
With this error:
```
Problem with mochawesome: TypeError: string is not a function
    at cleanTest (/home/iharrison/Projects/modules/node_modules/mochawesome/lib/mochawesome.js:252:21)
    at arrayMap (/home/iharrison/Projects/modules/node_modules/mochawesome/node_modules/lodash/index.js:1406:25)
    at Function.map (/home/iharrison/Projects/modules/node_modules/mochawesome/node_modules/lodash/index.js:6710:14)
    at cleanSuite (/home/iharrison/Projects/modules/node_modules/mochawesome/lib/mochawesome.js:162:22)
    at traverseSuites (/home/iharrison/Projects/modules/node_modules/mochawesome/lib/mochawesome.js:139:7)
    at Runner.<anonymous> (/home/iharrison/Projects/modules/node_modules/mochawesome/lib/mochawesome.js:77:9)
    at Runner.emit (events.js:129:20)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:791:12
    at /usr/local/lib/node_modules/mocha/lib/runner.js:644:9
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:284:14)
    at Immediate._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:320:5)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

This very well could be something else that's my fault... let me know if it is.

Thanks!

**Comment by riescorp-iharrison** [comment]
fwiw, I just noticed that report generation fails when the 'describe' is passed an empty string, like this: describe('', function() {

**Comment by adamgruber** [comment]
I have no issues generating a report with the `--recursive` flag set. It seems when `describe` has an empty title though, the test object has no `parent` property which is incorrect. I'm not exactly sure why this happens. Can you try making sure all your `describe`s have titles and see if it works?

**Comment by riescorp-iharrison** [comment]
That was it. The --recursive option was failing because of a test with an empty describe title. Thanks!
